apiVersion: v2
name: open-feature-operator
description: A feature flag operator for Kubernetes
type: application
version: 0.9.4
kubeVersion: '>=1.29.0-0'
appVersion: v0.9.3
home: https://openfeature.dev
icon: >-
  https://open-feature.github.io/open-feature-operator/chart/open-feature-operator/openfeature-logo.png
keywords:
  - OpenFeature
  - feature flags
  - feature toggles
  - OpenFeature Operator
  - open feature
  - open feature operator
  - OFO
sources:
  - https://github.com/open-feature/open-feature-operator
annotations:
  artifacthub.io/operator: 'true'
  artifacthub.io/category: integration-delivery
  artifacthub.io/links: |
    - name: support
      url: https://github.com/open-feature/open-feature-operator/issues
