apiVersion: v1
kind: Deployment
metadata:
  name: flagd-client-side-deployment
spec:
  selector:
    matchLabels:
      app: flagd-client-side
  template:
    labels:
      app: flagd-client-side
    spec:
      serviceAccountName: serviceAccountName
      containers:
        - name: flagd
          image: flagd:latest
          args:
            - "start"
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 9999
#          securityContext: TODO
#          resourceLimits: TODO