version: "2"

run:
  go: '1.25'

formatters:
  enable:
    - gofmt
    - gci

linters:
  default: none
  enable:
    - errorlint
    - containedctx
    - dogsled
    - nilnil
    - noctx
    - gocyclo
    - gocognit
    - funlen
    - dupl
  settings:
    gocyclo:
      min-complexity: 10
    gocognit:
      min-complexity: 20
    funlen:
      lines: 120
      statements: 120
  exclusions:
    rules:
      - linters:
          - containedctx
          - gocyclo
          - gocognit
          - funlen
        path: _test\.go
