apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-feature-operator-flagd-kubernetes-sync
rules:
- apiGroups:
  - core.openfeature.dev
  resources:
  - flagsourceconfigurations
  - featureflagconfigurations
  verbs:
  - get
  - watch
  - list
