apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: open-feature-operator-controller-manager-metrics-service
  namespace: '{{ include "chart.namespace" . }}'
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
