apiVersion: v1
kind: Service
metadata:
  annotations:
    cert-manager.io/inject-ca-from: open-feature-operator-system/webhook-cert
  name: open-feature-operator-webhook-service
  namespace: '{{ include "chart.namespace" . }}'
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
