apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: open-feature-operator-selfsigned-issuer
  namespace: open-feature-operator-system  
spec:
  selfSigned: {}
---  
apiVersion: cert-manager.io/v1
kind: Certificate  
metadata:  
  name: webhook-cert
  namespace: open-feature-operator-system  
spec:  
  secretName: sidecar-injector-certs  
  dnsNames:
    - open-feature-operator-webhook-service
    - open-feature-operator-webhook-service.open-feature-operator-system.svc  
    - open-feature-operator-webhook-service.open-feature-operator-system.svc.cluster.local  
  issuerRef:  
    name: open-feature-operator-selfsigned-issuer
