// Code generated by MockGen. DO NOT EDIT.
// Source: controllers/common/flagd-injector.go

// Package commonmock is a generated GoMock package.
package commonmock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	api "github.com/open-feature/open-feature-operator/apis/core/v1beta2"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	reflect "reflect"
)

// MockFlagdContainerInjector is a mock of IFlagdContainerInjector interface.
type MockFlagdContainerInjector struct {
	ctrl     *gomock.Controller
	recorder *MockFlagdContainerInjectorMockRecorder
}

// MockFlagdContainerInjectorMockRecorder is the mock recorder for MockFlagdContainerInjector.
type MockFlagdContainerInjectorMockRecorder struct {
	mock *MockFlagdContainerInjector
}

// NewMockFlagdContainerInjector creates a new mock instance.
func NewMockFlagdContainerInjector(ctrl *gomock.Controller) *MockFlagdContainerInjector {
	mock := &MockFlagdContainerInjector{ctrl: ctrl}
	mock.recorder = &MockFlagdContainerInjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlagdContainerInjector) EXPECT() *MockFlagdContainerInjectorMockRecorder {
	return m.recorder
}

// EnableClusterRoleBinding mocks base method.
func (m *MockFlagdContainerInjector) EnableClusterRoleBinding(ctx context.Context, namespace, serviceAccountName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableClusterRoleBinding", ctx, namespace, serviceAccountName)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableClusterRoleBinding indicates an expected call of EnableClusterRoleBinding.
func (mr *MockFlagdContainerInjectorMockRecorder) EnableClusterRoleBinding(ctx, namespace, serviceAccountName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableClusterRoleBinding", reflect.TypeOf((*MockFlagdContainerInjector)(nil).EnableClusterRoleBinding), ctx, namespace, serviceAccountName)
}

// InjectFlagd mocks base method.
func (m *MockFlagdContainerInjector) InjectFlagd(ctx context.Context, objectMeta *v10.ObjectMeta, podSpec *v1.PodSpec, flagSourceConfig *api.FeatureFlagSourceSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectFlagd", ctx, objectMeta, podSpec, flagSourceConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectFlagd indicates an expected call of InjectFlagd.
func (mr *MockFlagdContainerInjectorMockRecorder) InjectFlagd(ctx, objectMeta, podSpec, flagSourceConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectFlagd", reflect.TypeOf((*MockFlagdContainerInjector)(nil).InjectFlagd), ctx, objectMeta, podSpec, flagSourceConfig)
}
