apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
spec:
  dnsNames:
    - SERVICE_NAME.{{ include "chart.namespace" . }}.svc
    - SERVICE_NAME.{{ include "chart.namespace" . }}.svc.cluster.local
---
# The following manifests contain a self-signed issuer CR and a metrics certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-certs  # this name should match the one appeared in kustomizeconfig.yaml
spec:
  dnsNames:
    # SERVICE_NAME and SERVICE_NAMESPACE will be substituted by kustomize
    # replacements in the config/default/kustomization.yaml file.
    - SERVICE_NAME.{{ include "chart.namespace" . }}.svc
    - SERVICE_NAME.{{ include "chart.namespace" . }}.svc.cluster.local
