apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webhook-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: open-feature-operator-system/webhook-cert
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}