apiVersion: core.openfeature.dev/v1alpha1
kind: FeatureFlagConfiguration
metadata:
  name: featureflagconfiguration-sample
spec:
  provider:
    name: "flagD"
    credentials: 
      name: "sample-provider-secret"
      namespace: "default"
  featureFlagSpec: |
    {}
