name: Lint checks
on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".golangi.yml"
      - ".github/workflows/golangci-lint.yml"
      - "!docs/**"
env:
  # renovate: datasource=github-releases depName=golangci/golangci-lint
  GOLANGCI_LINT_VERSION: "v1.63.4"
  GO_VERSION: "~1.23"
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Workspace Init
        run: make workspace-init

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --config ./.golangci.yml -v
