name: Validate Helm Docs
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'chart/**'
defaults:
  run:
    shell: bash
jobs:
  check-helm-docs:
    name: Check helm documentation values
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3.8.2
        with:
          node-version: 16

      - name: Generate helm charts
        env:
          RELEASE_REGISTRY: ghcr.io/openfeature
        run: make helm-package

      - name: Install readme generator
        run: |
          git clone https://github.com/bitnami-labs/readme-generator-for-helm.git
          cd ./readme-generator-for-helm
          npm ci
          npm install --location=global ./
          cd ..

      - name: Check Helm doc up to date
        run: |
          cd ./chart/open-feature-operator/
          cp ./README.md ./README-old.md
          readme-generator --config $(pwd)/helm-docs-config.json --values=./values.yaml --readme=./README.md
          if ! cmp --quiet ./README-old.md ./README.md; then
            echo "The Helm values have changes that are not reflected in the readme. Please use ./.github/scripts/generate-helm-docs.sh to re-generate the docs."
            echo ""
            echo "=========== Diff ==========="
            diff -u ./README-old.md ./README.md
            exit 1
          else
            echo ""
            echo "Helm values documentation is correct!"
          fi
